# Generated by Django 4.2 on 2023-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=320, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
